# Generated by Django 4.2.25 on 2025-10-31 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_swipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pet1', to='accounts.pet')),
                ('pet2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pet2', to='accounts.pet')),
            ],
            options={
                'unique_together': {('pet1', 'pet2')},
            },
        ),
    ]
